/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Xunit;

using System;

namespace SpaceTraders.Test.Model
{
    /// <summary>
    ///  Class for testing Ship
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ShipTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Ship
        //private Ship instance;

        public ShipTests()
        {
            // TODO uncomment below to create an instance of Ship
            //instance = new Ship();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Ship
        /// </summary>
        [Fact]
        public void ShipInstanceTest()
        {
            // TODO uncomment below to test "IsType" Ship
            //Assert.IsType<Ship>(instance);
        }

        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Fact]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }

        /// <summary>
        /// Test the property 'Registration'
        /// </summary>
        [Fact]
        public void RegistrationTest()
        {
            // TODO unit test for the property 'Registration'
        }

        /// <summary>
        /// Test the property 'Nav'
        /// </summary>
        [Fact]
        public void NavTest()
        {
            // TODO unit test for the property 'Nav'
        }

        /// <summary>
        /// Test the property 'Crew'
        /// </summary>
        [Fact]
        public void CrewTest()
        {
            // TODO unit test for the property 'Crew'
        }

        /// <summary>
        /// Test the property 'Frame'
        /// </summary>
        [Fact]
        public void FrameTest()
        {
            // TODO unit test for the property 'Frame'
        }

        /// <summary>
        /// Test the property 'Reactor'
        /// </summary>
        [Fact]
        public void ReactorTest()
        {
            // TODO unit test for the property 'Reactor'
        }

        /// <summary>
        /// Test the property 'Engine'
        /// </summary>
        [Fact]
        public void EngineTest()
        {
            // TODO unit test for the property 'Engine'
        }

        /// <summary>
        /// Test the property 'Modules'
        /// </summary>
        [Fact]
        public void ModulesTest()
        {
            // TODO unit test for the property 'Modules'
        }

        /// <summary>
        /// Test the property 'Mounts'
        /// </summary>
        [Fact]
        public void MountsTest()
        {
            // TODO unit test for the property 'Mounts'
        }

        /// <summary>
        /// Test the property 'Cargo'
        /// </summary>
        [Fact]
        public void CargoTest()
        {
            // TODO unit test for the property 'Cargo'
        }

        /// <summary>
        /// Test the property 'Fuel'
        /// </summary>
        [Fact]
        public void FuelTest()
        {
            // TODO unit test for the property 'Fuel'
        }
    }
}
