/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace SpaceTraders.Model
{
    /// <summary>
    /// WaypointTrait
    /// </summary>
    [DataContract(Name = "WaypointTrait")]
    public partial class WaypointTrait : IEquatable<WaypointTrait>, IValidatableObject
    {
        /// <summary>
        /// The unique identifier of the trait.
        /// </summary>
        /// <value>The unique identifier of the trait.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SymbolEnum
        {
            /// <summary>
            /// Enum UNCHARTED for value: UNCHARTED
            /// </summary>
            [EnumMember(Value = "UNCHARTED")]
            UNCHARTED,

            /// <summary>
            /// Enum UNDERCONSTRUCTION for value: UNDER_CONSTRUCTION
            /// </summary>
            [EnumMember(Value = "UNDER_CONSTRUCTION")]
            UNDERCONSTRUCTION,

            /// <summary>
            /// Enum MARKETPLACE for value: MARKETPLACE
            /// </summary>
            [EnumMember(Value = "MARKETPLACE")]
            MARKETPLACE,

            /// <summary>
            /// Enum SHIPYARD for value: SHIPYARD
            /// </summary>
            [EnumMember(Value = "SHIPYARD")]
            SHIPYARD,

            /// <summary>
            /// Enum OUTPOST for value: OUTPOST
            /// </summary>
            [EnumMember(Value = "OUTPOST")]
            OUTPOST,

            /// <summary>
            /// Enum SCATTEREDSETTLEMENTS for value: SCATTERED_SETTLEMENTS
            /// </summary>
            [EnumMember(Value = "SCATTERED_SETTLEMENTS")]
            SCATTEREDSETTLEMENTS,

            /// <summary>
            /// Enum SPRAWLINGCITIES for value: SPRAWLING_CITIES
            /// </summary>
            [EnumMember(Value = "SPRAWLING_CITIES")]
            SPRAWLINGCITIES,

            /// <summary>
            /// Enum MEGASTRUCTURES for value: MEGA_STRUCTURES
            /// </summary>
            [EnumMember(Value = "MEGA_STRUCTURES")]
            MEGASTRUCTURES,

            /// <summary>
            /// Enum PIRATEBASE for value: PIRATE_BASE
            /// </summary>
            [EnumMember(Value = "PIRATE_BASE")]
            PIRATEBASE,

            /// <summary>
            /// Enum OVERCROWDED for value: OVERCROWDED
            /// </summary>
            [EnumMember(Value = "OVERCROWDED")]
            OVERCROWDED,

            /// <summary>
            /// Enum HIGHTECH for value: HIGH_TECH
            /// </summary>
            [EnumMember(Value = "HIGH_TECH")]
            HIGHTECH,

            /// <summary>
            /// Enum CORRUPT for value: CORRUPT
            /// </summary>
            [EnumMember(Value = "CORRUPT")]
            CORRUPT,

            /// <summary>
            /// Enum BUREAUCRATIC for value: BUREAUCRATIC
            /// </summary>
            [EnumMember(Value = "BUREAUCRATIC")]
            BUREAUCRATIC,

            /// <summary>
            /// Enum TRADINGHUB for value: TRADING_HUB
            /// </summary>
            [EnumMember(Value = "TRADING_HUB")]
            TRADINGHUB,

            /// <summary>
            /// Enum INDUSTRIAL for value: INDUSTRIAL
            /// </summary>
            [EnumMember(Value = "INDUSTRIAL")]
            INDUSTRIAL,

            /// <summary>
            /// Enum BLACKMARKET for value: BLACK_MARKET
            /// </summary>
            [EnumMember(Value = "BLACK_MARKET")]
            BLACKMARKET,

            /// <summary>
            /// Enum RESEARCHFACILITY for value: RESEARCH_FACILITY
            /// </summary>
            [EnumMember(Value = "RESEARCH_FACILITY")]
            RESEARCHFACILITY,

            /// <summary>
            /// Enum MILITARYBASE for value: MILITARY_BASE
            /// </summary>
            [EnumMember(Value = "MILITARY_BASE")]
            MILITARYBASE,

            /// <summary>
            /// Enum SURVEILLANCEOUTPOST for value: SURVEILLANCE_OUTPOST
            /// </summary>
            [EnumMember(Value = "SURVEILLANCE_OUTPOST")]
            SURVEILLANCEOUTPOST,

            /// <summary>
            /// Enum EXPLORATIONOUTPOST for value: EXPLORATION_OUTPOST
            /// </summary>
            [EnumMember(Value = "EXPLORATION_OUTPOST")]
            EXPLORATIONOUTPOST,

            /// <summary>
            /// Enum MINERALDEPOSITS for value: MINERAL_DEPOSITS
            /// </summary>
            [EnumMember(Value = "MINERAL_DEPOSITS")]
            MINERALDEPOSITS,

            /// <summary>
            /// Enum COMMONMETALDEPOSITS for value: COMMON_METAL_DEPOSITS
            /// </summary>
            [EnumMember(Value = "COMMON_METAL_DEPOSITS")]
            COMMONMETALDEPOSITS,

            /// <summary>
            /// Enum PRECIOUSMETALDEPOSITS for value: PRECIOUS_METAL_DEPOSITS
            /// </summary>
            [EnumMember(Value = "PRECIOUS_METAL_DEPOSITS")]
            PRECIOUSMETALDEPOSITS,

            /// <summary>
            /// Enum RAREMETALDEPOSITS for value: RARE_METAL_DEPOSITS
            /// </summary>
            [EnumMember(Value = "RARE_METAL_DEPOSITS")]
            RAREMETALDEPOSITS,

            /// <summary>
            /// Enum METHANEPOOLS for value: METHANE_POOLS
            /// </summary>
            [EnumMember(Value = "METHANE_POOLS")]
            METHANEPOOLS,

            /// <summary>
            /// Enum ICECRYSTALS for value: ICE_CRYSTALS
            /// </summary>
            [EnumMember(Value = "ICE_CRYSTALS")]
            ICECRYSTALS,

            /// <summary>
            /// Enum EXPLOSIVEGASES for value: EXPLOSIVE_GASES
            /// </summary>
            [EnumMember(Value = "EXPLOSIVE_GASES")]
            EXPLOSIVEGASES,

            /// <summary>
            /// Enum STRONGMAGNETOSPHERE for value: STRONG_MAGNETOSPHERE
            /// </summary>
            [EnumMember(Value = "STRONG_MAGNETOSPHERE")]
            STRONGMAGNETOSPHERE,

            /// <summary>
            /// Enum VIBRANTAURORAS for value: VIBRANT_AURORAS
            /// </summary>
            [EnumMember(Value = "VIBRANT_AURORAS")]
            VIBRANTAURORAS,

            /// <summary>
            /// Enum SALTFLATS for value: SALT_FLATS
            /// </summary>
            [EnumMember(Value = "SALT_FLATS")]
            SALTFLATS,

            /// <summary>
            /// Enum CANYONS for value: CANYONS
            /// </summary>
            [EnumMember(Value = "CANYONS")]
            CANYONS,

            /// <summary>
            /// Enum PERPETUALDAYLIGHT for value: PERPETUAL_DAYLIGHT
            /// </summary>
            [EnumMember(Value = "PERPETUAL_DAYLIGHT")]
            PERPETUALDAYLIGHT,

            /// <summary>
            /// Enum PERPETUALOVERCAST for value: PERPETUAL_OVERCAST
            /// </summary>
            [EnumMember(Value = "PERPETUAL_OVERCAST")]
            PERPETUALOVERCAST,

            /// <summary>
            /// Enum DRYSEABEDS for value: DRY_SEABEDS
            /// </summary>
            [EnumMember(Value = "DRY_SEABEDS")]
            DRYSEABEDS,

            /// <summary>
            /// Enum MAGMASEAS for value: MAGMA_SEAS
            /// </summary>
            [EnumMember(Value = "MAGMA_SEAS")]
            MAGMASEAS,

            /// <summary>
            /// Enum SUPERVOLCANOES for value: SUPERVOLCANOES
            /// </summary>
            [EnumMember(Value = "SUPERVOLCANOES")]
            SUPERVOLCANOES,

            /// <summary>
            /// Enum ASHCLOUDS for value: ASH_CLOUDS
            /// </summary>
            [EnumMember(Value = "ASH_CLOUDS")]
            ASHCLOUDS,

            /// <summary>
            /// Enum VASTRUINS for value: VAST_RUINS
            /// </summary>
            [EnumMember(Value = "VAST_RUINS")]
            VASTRUINS,

            /// <summary>
            /// Enum MUTATEDFLORA for value: MUTATED_FLORA
            /// </summary>
            [EnumMember(Value = "MUTATED_FLORA")]
            MUTATEDFLORA,

            /// <summary>
            /// Enum TERRAFORMED for value: TERRAFORMED
            /// </summary>
            [EnumMember(Value = "TERRAFORMED")]
            TERRAFORMED,

            /// <summary>
            /// Enum EXTREMETEMPERATURES for value: EXTREME_TEMPERATURES
            /// </summary>
            [EnumMember(Value = "EXTREME_TEMPERATURES")]
            EXTREMETEMPERATURES,

            /// <summary>
            /// Enum EXTREMEPRESSURE for value: EXTREME_PRESSURE
            /// </summary>
            [EnumMember(Value = "EXTREME_PRESSURE")]
            EXTREMEPRESSURE,

            /// <summary>
            /// Enum DIVERSELIFE for value: DIVERSE_LIFE
            /// </summary>
            [EnumMember(Value = "DIVERSE_LIFE")]
            DIVERSELIFE,

            /// <summary>
            /// Enum SCARCELIFE for value: SCARCE_LIFE
            /// </summary>
            [EnumMember(Value = "SCARCE_LIFE")]
            SCARCELIFE,

            /// <summary>
            /// Enum FOSSILS for value: FOSSILS
            /// </summary>
            [EnumMember(Value = "FOSSILS")]
            FOSSILS,

            /// <summary>
            /// Enum WEAKGRAVITY for value: WEAK_GRAVITY
            /// </summary>
            [EnumMember(Value = "WEAK_GRAVITY")]
            WEAKGRAVITY,

            /// <summary>
            /// Enum STRONGGRAVITY for value: STRONG_GRAVITY
            /// </summary>
            [EnumMember(Value = "STRONG_GRAVITY")]
            STRONGGRAVITY,

            /// <summary>
            /// Enum CRUSHINGGRAVITY for value: CRUSHING_GRAVITY
            /// </summary>
            [EnumMember(Value = "CRUSHING_GRAVITY")]
            CRUSHINGGRAVITY,

            /// <summary>
            /// Enum TOXICATMOSPHERE for value: TOXIC_ATMOSPHERE
            /// </summary>
            [EnumMember(Value = "TOXIC_ATMOSPHERE")]
            TOXICATMOSPHERE,

            /// <summary>
            /// Enum CORROSIVEATMOSPHERE for value: CORROSIVE_ATMOSPHERE
            /// </summary>
            [EnumMember(Value = "CORROSIVE_ATMOSPHERE")]
            CORROSIVEATMOSPHERE,

            /// <summary>
            /// Enum BREATHABLEATMOSPHERE for value: BREATHABLE_ATMOSPHERE
            /// </summary>
            [EnumMember(Value = "BREATHABLE_ATMOSPHERE")]
            BREATHABLEATMOSPHERE,

            /// <summary>
            /// Enum THINATMOSPHERE for value: THIN_ATMOSPHERE
            /// </summary>
            [EnumMember(Value = "THIN_ATMOSPHERE")]
            THINATMOSPHERE,

            /// <summary>
            /// Enum JOVIAN for value: JOVIAN
            /// </summary>
            [EnumMember(Value = "JOVIAN")]
            JOVIAN,

            /// <summary>
            /// Enum ROCKY for value: ROCKY
            /// </summary>
            [EnumMember(Value = "ROCKY")]
            ROCKY,

            /// <summary>
            /// Enum VOLCANIC for value: VOLCANIC
            /// </summary>
            [EnumMember(Value = "VOLCANIC")]
            VOLCANIC,

            /// <summary>
            /// Enum FROZEN for value: FROZEN
            /// </summary>
            [EnumMember(Value = "FROZEN")]
            FROZEN,

            /// <summary>
            /// Enum SWAMP for value: SWAMP
            /// </summary>
            [EnumMember(Value = "SWAMP")]
            SWAMP,

            /// <summary>
            /// Enum BARREN for value: BARREN
            /// </summary>
            [EnumMember(Value = "BARREN")]
            BARREN,

            /// <summary>
            /// Enum TEMPERATE for value: TEMPERATE
            /// </summary>
            [EnumMember(Value = "TEMPERATE")]
            TEMPERATE,

            /// <summary>
            /// Enum JUNGLE for value: JUNGLE
            /// </summary>
            [EnumMember(Value = "JUNGLE")]
            JUNGLE,

            /// <summary>
            /// Enum OCEAN for value: OCEAN
            /// </summary>
            [EnumMember(Value = "OCEAN")]
            OCEAN,

            /// <summary>
            /// Enum RADIOACTIVE for value: RADIOACTIVE
            /// </summary>
            [EnumMember(Value = "RADIOACTIVE")]
            RADIOACTIVE,

            /// <summary>
            /// Enum MICROGRAVITYANOMALIES for value: MICRO_GRAVITY_ANOMALIES
            /// </summary>
            [EnumMember(Value = "MICRO_GRAVITY_ANOMALIES")]
            MICROGRAVITYANOMALIES,

            /// <summary>
            /// Enum DEBRISCLUSTER for value: DEBRIS_CLUSTER
            /// </summary>
            [EnumMember(Value = "DEBRIS_CLUSTER")]
            DEBRISCLUSTER,

            /// <summary>
            /// Enum DEEPCRATERS for value: DEEP_CRATERS
            /// </summary>
            [EnumMember(Value = "DEEP_CRATERS")]
            DEEPCRATERS,

            /// <summary>
            /// Enum SHALLOWCRATERS for value: SHALLOW_CRATERS
            /// </summary>
            [EnumMember(Value = "SHALLOW_CRATERS")]
            SHALLOWCRATERS,

            /// <summary>
            /// Enum UNSTABLECOMPOSITION for value: UNSTABLE_COMPOSITION
            /// </summary>
            [EnumMember(Value = "UNSTABLE_COMPOSITION")]
            UNSTABLECOMPOSITION,

            /// <summary>
            /// Enum HOLLOWEDINTERIOR for value: HOLLOWED_INTERIOR
            /// </summary>
            [EnumMember(Value = "HOLLOWED_INTERIOR")]
            HOLLOWEDINTERIOR,

            /// <summary>
            /// Enum STRIPPED for value: STRIPPED
            /// </summary>
            [EnumMember(Value = "STRIPPED")]
            STRIPPED
        }

        /// <summary>
        /// The unique identifier of the trait.
        /// </summary>
        /// <value>The unique identifier of the trait.</value>
        [DataMember(Name = "symbol", IsRequired = true, EmitDefaultValue = true)]
        public SymbolEnum Symbol { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="WaypointTrait" /> class.
        /// </summary>
        [JsonConstructor]
        protected WaypointTrait() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WaypointTrait" /> class.
        /// </summary>
        /// <param name="symbol">The unique identifier of the trait. (required).</param>
        /// <param name="name">The name of the trait. (required).</param>
        /// <param name="description">A description of the trait. (required).</param>
        public WaypointTrait(SymbolEnum symbol = default, string? name = default, string? description = default)
        {
            this.Symbol = symbol;
            // to ensure "name" is required (not null)
            ArgumentNullException.ThrowIfNull(name);

            this.Name = name;
            // to ensure "description" is required (not null)
            ArgumentNullException.ThrowIfNull(description);

            this.Description = description;
        }

        /// <summary>
        /// The name of the trait.
        /// </summary>
        /// <value>The name of the trait.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// A description of the trait.
        /// </summary>
        /// <value>A description of the trait.</value>
        [DataMember(Name = "description", IsRequired = true, EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WaypointTrait {\n");
            sb.Append("  Symbol: ").Append(Symbol).Append('\n');
            sb.Append("  Name: ").Append(Name).Append('\n');
            sb.Append("  Description: ").Append(Description).Append('\n');
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WaypointTrait);
        }

        /// <summary>
        /// Returns true if WaypointTrait instances are equal
        /// </summary>
        /// <param name="input">Instance of WaypointTrait to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WaypointTrait input)
        {
            if (input == null)
            {
                return false;
            }

            return
                (
                    this.Symbol == input.Symbol ||
                    this.Symbol.Equals(input.Symbol)
                ) &&
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) &&
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Symbol.GetHashCode();
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }

                if (this.Description != null)
                {
                    hashCode = (hashCode * 59) + this.Description.GetHashCode();
                }

                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
