/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using Xunit;
using SpaceTraders.Api;
// uncomment below to import models
//using SpaceTraders.Model;

namespace SpaceTraders.Test.Api
{
    /// <summary>
    ///  Class for testing FactionsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class FactionsApiTests : IDisposable
    {
        private readonly FactionsApi mInstance;

        public FactionsApiTests()
        {
            mInstance = new FactionsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FactionsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' FactionsApi
            //Assert.IsType<FactionsApi>(instance);
        }

        /// <summary>
        /// Test GetFaction
        /// </summary>
        [Fact]
        public void GetFactionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string factionSymbol = null;
            //var response = instance.GetFaction(factionSymbol);
            //Assert.IsType<GetFaction200Response>(response);
        }

        /// <summary>
        /// Test GetFactions
        /// </summary>
        [Fact]
        public void GetFactionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? limit = null;
            //var response = instance.GetFactions(page, limit);
            //Assert.IsType<GetFactions200Response>(response);
        }
    }
}
